### ISSUE TITLE
Date was not created in the FileHeader

### ISSUE THREAD

**Issue by nmyneedu** [Cinchoo/ChoETL.NACHA#10]
I downloaded the nuget package of these project and ran locally in my machine, I am able to generate the file but in the file header where we need to mention current date and time its not working insted its displaying 0101010000. can you help me in fixing that issue.

**Comment by Cinchoo** [comment]
Found a bug in the ChoETL library, ignoring to evaluate default value expression on object members. Fix the issue, pushed the code. Take the latest and try it.

**Comment by nmyneedu** [comment]
Sure thanks  Chincho .. Is there any way you can expose  _NACHABatchHeaderRecord.CompanyID and  _NACHABatchHeaderRecord.OriginatingDFIID property to Natcha Batch header and  _activeEntry.TraceNumber in debit and credit entry record to public because in my code I use in different way that would be a great help you are setiing values from file header but I need in different way.
