### ISSUE TITLE
Company name and company Id are set to default values from file header in batch header 

### ISSUE THREAD

**Issue by nmyneedu** [Cinchoo/ChoETL.NACHA#11]

**Comment by Cinchoo** [comment]
Exposed these members on CreateBatch() method to override them. Try it now.

**Comment by nmyneedu** [comment]
Thanks Cincho.. Is there any way you pushed the latest code into nuget package??

**Comment by Cinchoo** [comment]
will do shortly

**Comment by nmyneedu** [comment]
Hey Chinchoo sorry to bug you once again I found these while creating Nacha Record when we enter 
 config.DestinationBankRoutingNumber as 10 digits with empty as first character then both i**n debit and credit entry record and in Batch control record tracenumber** we are getting only 7 digits from routing number.

For example if we enter  config.DestinationBankRoutingNumber as " 123456789"
then both in **# debit and credit entry record and in batch control record** the tracenumber is generated like this "0 12345670000001" insted of "0123456780000001"

**Comment by Cinchoo** [comment]
It is a bug, fixed and pushed the changes. Try it.

**Comment by nmyneedu** [comment]
Thanks Cinchoo.. can you push these all changes to nuget because I am using nuget package in my project..Thanks a lot for your help

**Comment by Cinchoo** [comment]
Pushed. Thanks for reporting it.

**Comment by nmyneedu** [comment]
Hi Chinchoo.. When I downloaded nuget package and try to run my code I am facing these issue.

Exception compiling code fragment: 

	return ((v.Length == 9 && !v.Where(c => !Char.IsDigit(c)).Any()) || (v.Length == 10 && v[0] == ' ' && !v.Skip(1).Where(c => !Char.IsDigit(c)).Any()));

Exceptions:
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.VisualStudio.Web.PageInspector.Loader.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Antlr3.Runtime.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Autofac.dll' could not be found


My .net version is **4.6.1**

**Comment by nmyneedu** [comment]
Highlevel Exception {"Failed to write line for 'ChoETL.NACHA.ChoNACHAFileHeaderRecord' object."}

Even i am facing the same error when i use the source code in my project .. It works only when I comment those data annotations part in File header records place.

**Comment by Cinchoo** [comment]
Interesting, Assuming your code is ASP.NET application? Am I right?

If so, can you create sample console app and give it a try?

**Comment by nmyneedu** [comment]
its working with new console application but problem happens only when I call the code using Web Api Application . I placed the reference  in class library project and calling form web Api application

**Comment by Cinchoo** [comment]
Can you please look at the below link and see if this can help u on anyway

https://stackoverflow.com/questions/33319675/the-codedom-provider-type-microsoft-codedom-providers-dotnetcompilerplatform-cs

**Comment by nmyneedu** [comment]
I tried all this ... but no result 
 _refAssemblies = AppDomain.CurrentDomain
                                        .GetAssemblies()
                                        .Where(a => !a.IsDynamic && !a.Location.IsNullOrWhiteSpace())                                      
                                        .Select(a => a.Location);

problem is its loading all the references from web api, so dll are in GAC and some pulling form temp location and at the ends its showing 64 files are msiing in these line 

var res = codeDomProvider.CompileAssemblyFromSource(compilerParameters, statement);

                if (res.Errors.Count > 0)

**Comment by nmyneedu** [comment]
Exception compiling code fragment: 

	return v[0] != '0' && Regex.IsMatch(v, "^[0-9]+$", RegexOptions.Compiled);

Exceptions:
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.VisualStudio.Web.PageInspector.Loader.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Antlr3.Runtime.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Autofac.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Autofac.Integration.WebApi.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'BankAccount.Contract.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'ChoETL.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'ChoETL.NACHA.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'EntityFramework.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'EntityFramework.SqlServer.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'FluentValidation.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'log4net.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.AI.Agent.Intercept.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.AI.DependencyCollector.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.AI.PerfCounterCollector.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.AI.ServerTelemetryChannel.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.AI.Web.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.AI.WindowsServer.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.ApplicationInsights.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.AspNet.Identity.Core.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.AspNet.Identity.EntityFramework.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.AspNet.Identity.Owin.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.Owin.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.Owin.Host.SystemWeb.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.Owin.Security.Cookies.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.Owin.Security.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.Owin.Security.Facebook.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.Owin.Security.Google.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.Owin.Security.MicrosoftAccount.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.Owin.Security.OAuth.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.Owin.Security.Twitter.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.Web.Infrastructure.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'NachaService.Api.Contracts.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'NachaService.Core.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'NachaService.Data.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'NachaService.DI.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'NachaService.UI.Integration.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'NachaService.WebApi.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Newtonsoft.Json.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'NLog.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Owin.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Purplelight.Framework.Autofac.Integration.WebApi.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'RestSharp.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Swashbuckle.Core.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'System.Net.Http.Formatting.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'System.Web.Helpers.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'System.Web.Http.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'System.Web.Http.Owin.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'System.Web.Http.WebHost.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'System.Web.Mvc.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'System.Web.Optimization.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'System.Web.Razor.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'System.Web.WebPages.Deployment.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'System.Web.WebPages.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'System.Web.WebPages.Razor.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'WebActivatorEx.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'WebGrease.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.VisualStudio.Web.PageInspector.Runtime.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.VisualStudio.Web.PageInspector.Tracing.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'App_global.asax.d07v-ndx.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'App_Web_ucdldrjb.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'App_Web_py51mlew.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'App_Web_fwlnvutd.dll' could not be found
	Line number 0, Error Number: CS0006, Metadata file 'Microsoft.VisualStudio.Web.PageInspector.HtmlParser.dll' could not be found

**Comment by nmyneedu** [comment]
its pulling all the dll from webApi project these are all references in my web api project

**Comment by Cinchoo** [comment]
Try this. Just remove this section from web.config if you have it

<system.codedom>
   <compilers>
     <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:6 /nowarn:1659;1699;1701" />
     <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:14 /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" />
   </compilers>
</system.codedom>

**Comment by nmyneedu** [comment]
Nope no luck I tried all these means ...

**Comment by nmyneedu** [comment]
It  failingonly when we hit with web api, and its only in the line where there is **ChoCustomCodeValidator** 2 records are in nachafileheaderrecord and 1 record in nachabatchheaderrecord

**NachaFileHeaderRecord:**

 [ChoFixedLengthRecordField(3,10)]
        //[ChoCustomCodeValidator("v => ((v.Length == 9 && !v.Where(c => !Char.IsDigit(c)).Any()) || (v.Length == 10 && v[0] == ' ' && !v.Skip(1).Where(c => !Char.IsDigit(c)).Any()))", ErrorMessage = "Invalid ImmediateDestination value found.")]
        public string ImmediateDestination { get; set; }

    
        [ChoFixedLengthRecordField(13, 10)]
        //[ChoCustomCodeValidator("v => ((v.Length == 9 && !v.Where(c => !Char.IsDigit(c)).Any()) || (v.Length == 10 && v[0] == ' ' && !v.Skip(1).Where(c => !Char.IsDigit(c)).Any()) || (v.Length == 10 && !v.Where(c => !Char.IsDigit(c)).Any()))", ErrorMessage = "Invalid ImmediateOrigin value found.")]
        public string ImmediateOrigin { get; set; }


and in NachaBatchHeaderRecord:
    [ChoFixedLengthRecordField(78, 1)]
        [DefaultValue('1')]
       // [ChoCustomCodeValidator(@"v => v[0] != '0' && Regex.IsMatch(v, ""^[0-9]+$"", RegexOptions.Compiled)", ErrorMessage = "OriginatorStatusCode must be 1-9.", ParamType = typeof(string))]
        public char OriginatorStatusCode { get; set; }

**Comment by Cinchoo** [comment]
let me take a look and see if there alternative way to handle this.

Are you sure these are the 2 validators failing at?

**Comment by nmyneedu** [comment]
Yes totally 4 places it is getting failed two in nachafileheader and one in nachabatchheader and one in nachaentrydetailrecord all related to same chocustomvalidator

**Comment by Cinchoo** [comment]
ok, Will convert them to custom validators. Will give you update shortly.

**Comment by nmyneedu** [comment]
Thanks chinchoo really looking forward to those changes

**Comment by Cinchoo** [comment]
Replaced them with custom validators. Pull the latest and try it, Let me know how it goes.

**Comment by nmyneedu** [comment]
Object reference not set to an instance of an object. error in 
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public class ChoOriginatorStatusCodeAttribute : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            string v = value as string;
            return v[0] != '0' && Regex.IsMatch(v, "^[0-9]+$", RegexOptions.Compiled);
        }
    }

**Comment by nmyneedu** [comment]
Same exception for these custom validation also
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public class ChoIsDigitAttribute : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            string v = value as string;
            return Char.IsDigit(v[0]);
        }
    }

**Comment by Cinchoo** [comment]
Oops, found the issue. Fixed it. Pls try and let me know

**Comment by nmyneedu** [comment]
Thanks cinchoo it fixed that issue....I will create whole new debit file and ll let you know the result

**Comment by nmyneedu** [comment]
Hi Cincho... I am able to generate nacha debit successfully.. Can you please push these changes to nuget package that would be great help.. Because I need to integrate nuget package to my project and should be able to hit through webapi..Thanks for your help

**Comment by nmyneedu** [comment]
Hey Chinchoo.. One more thing I just found now in batch control record the companyid should be from the copmany id from batch header not from file header originating id
            _NACHABatchControlRecord.CompanyID = _configuration.OriginatingCompanyId;
it should be from batch header not from configuration

**Comment by nmyneedu** [comment]
Sorry I forgot that yesterday after creating file I just saw now

**Comment by nmyneedu** [comment]
By changing the record in the batchcontrol to 

_NACHABatchControlRecord.CompanyID = CompanyID;

where CompanyId is property ChoNachaBatchWriter it works can you push the same code to source so it will work for every one.

**Comment by Cinchoo** [comment]
Corrected the BatchControl CompanyId, OriginatingDFIID issue. Pushed the changes to Git/Nuget.
