### ISSUE TITLE
Turn off or disable logging option?

### ISSUE THREAD

**Issue by beaudetious** [Cinchoo/ChoETL.NACHA#12]
How can I do this currently? I am getting a log output file each time I create an ACH that has no useful information to me (currently).

I searched the project for the term "Time taken to run the application" and could not find where it is used.

Thanks.

**Comment by Cinchoo** [comment]
Add this line at the Main() entry of your application, to control the logging

```
static void Main(string[] args)
{
     ChoETL.ChoETLFrxBootstrap.TraceLevel = System.Diagnostics.TraceLevel.Off;
}
```

**Comment by beaudetious** [comment]
That did the trick. Thanks.
