### ISSUE TITLE
ChoETA Licences is GPL3 non obvious when ChoETL.NATCHA is MIT

### ISSUE THREAD

**Issue by jbtule** [Cinchoo/ChoETL.NACHA#14]
While nothing is preventing ChoETL.NACHA from being licensed MIT. It's a bit precarious when it's dependent on  ChoETA which is GPLv3.   It means that any project consuming ChoETL.NACHA must be GPLV3 compliant, but it's not obvious since ChoETL.NACHA is MIT licensed.

**Comment by Cinchoo** [comment]
Fixed it. Let me know.
