### ISSUE TITLE
EntryHash in batch control and file control record

### ISSUE THREAD

**Issue by block01** [Cinchoo/ChoETL.NACHA#15]
In EntryHash field, when total value exceeds 10 character length, is it possible to ignore the overflow out of the high order (leftmost) position instead of the right order position?

Example: 
 EntryHash: 98765432000
     Current: 9876543200
Requested: 8765432000

Thank you.

**Comment by Cinchoo** [comment]
Applied fix in ChoETL library. Take the latest code or nuget to resolve this issue. Let me know.

**Comment by block01** [comment]
Works like a charm. Thank you!
