### ISSUE TITLE
When generating file "Entry / Addenda Count" field in Batch Control are always 0

### ISSUE THREAD

**Issue by etwina** [Cinchoo/ChoETL.NACHA#2]
am I missing something ?
(I have updated code today)

**Comment by etwina** [comment]
When generating file "Entry / Addenda Count" field in Batch and File Control - only Addendas are being counted. This field should specify count of Addendas+Entries

**Comment by etwina** [comment]
possible solution:
![image](https://cloud.githubusercontent.com/assets/3801343/24502204/741ad9a8-1555-11e7-854f-448491b563e5.png)

Add "IncAddendaRecordCountBy" to EntryDetails UpdateStat()

**Comment by Cinchoo** [comment]
Corrected. Updated the fix to repository.
