### ISSUE TITLE
OriginatingCompanyId allow characters

### ISSUE THREAD

**Issue by afzaluddinSyed** [Cinchoo/ChoETL.NACHA#21]
OriginatingCompanyId is not accepting characters few companyid have a starting character, adding character to the OriginatingCompanyId is causing empty header record in file.

**Comment by Cinchoo** [comment]
Added `ChoNACHAConfiguration.TurnOffOriginatingCompanyIdValidation` to control the validation of this member. Please take the latest and give it a try.

Will be pushing update to nuget shortly.
