### ISSUE TITLE
FileControlRecord not created when row length is not 94 characters

### ISSUE THREAD

**Issue by lalberto-tis** [Cinchoo/ChoETL.NACHA#24]
If FileControlRecord does not have 94 characters length, the record is not created and throws an exception.

This is an example of FileControl row:
9002590002614000209586395558861000000000000015453666250

This is the exception:
![image](https://user-images.githubusercontent.com/23344102/56623957-3660fa80-65fc-11e9-884f-4fe24335f631.png)

The issue:
![image](https://user-images.githubusercontent.com/23344102/56623992-509ad880-65fc-11e9-8085-52b743e98094.png)

It's not being validated in case of empty or row length < 94

**Comment by Cinchoo** [comment]
Thanks for reporting it. Identified the issue, putting fix. Will update once code commited.

**Comment by Cinchoo** [comment]
new package released with fixes. Take the latest and try it. Let me know.
