### ISSUE TITLE
Convert data to NACHA

### ISSUE THREAD

**Issue by kmehmoodkhan** [Cinchoo/ChoETL.NACHA#25]
![image](https://user-images.githubusercontent.com/27416360/68321207-1cdc5780-00e3-11ea-90ea-bcd2b9c57760.png)

Hi, can you please guide me on how to use this package to generate Nacha file using the data from the excel sheet. For reference screenshot is attached. Thank you

**Comment by Cinchoo** [comment]
You will need some package (google it) to read the excel file. If the file is in CSV format, you can use ChoETL for parsing the file, then use this library to create the NACHA file. Hope this help.

**Comment by kmehmoodkhan** [comment]
Thank you for your reply. Yes I understand that, we need to read excel file for data. My question is how to map the fields shown in the excel to this method 
![image](https://user-images.githubusercontent.com/27416360/68454030-2f58ad00-0219-11ea-80e2-c99c1128d581.png)

**Comment by Cinchoo** [comment]
you may want to use NACHA spec (google it) to do the mapping.
