### ISSUE TITLE
MemoryStream not working 

### ISSUE THREAD

**Issue by Caverax** [Cinchoo/ChoETL.NACHA#27]
I'm using a memory stream as I want to return the file in a file download directly and it doesn't seem to be updated as I'm writing the information. 

I can't copy the exact code but basically doing : 

var nachaWriter = new ChoNACHAWriter(stream, config);

then create a batch using this writer and entries using the batch writer. Nothing seems to update the stream in the back.. stream length stays at 0 at all time and file end up empty in the end.

I don't see anything like write to stream in the end so I'm not sure how what the problem is.

Pier

**Comment by Caverax** [comment]
I ended up using the StreamWriter constructor instead and having to flush the writer to get my result. Closed.

**Comment by rohitv82** [comment]
i am facing same issue. can you share how you resolved this issue

**Comment by tkennedy13** [comment]
Same issue. I'm using ChoETL.NACHA.NETStandard 1.0.2.3. I used the code off the main Github page, just adding the memory stream. 

```
ChoNACHAConfiguration config = new ChoNACHAConfiguration();
config.DestinationBankRoutingNumber = "123456789";
config.OriginatingCompanyId = "123456789";
config.DestinationBankName = "PNC Bank";
config.OriginatingCompanyName = "Microsoft Inc.";
config.ReferenceCode = "Internal Use Only.";
config.BlockCount = 10;

using (var stream = new MemoryStream())
{
	using (var nachaWriter = new ChoNACHAWriter(stream, config))
	{
		using (var bw1 = nachaWriter.CreateBatch(200))
		{
			using (var entry1 = bw1.CreateDebitEntryDetail(20, "123456789", "1313131313", 22.505M, "ID Number", "ID Name", "Desc Data"))
			{
				entry1.CreateAddendaRecord("Monthly bill");
			}
			using (var entry2 = bw1.CreateCreditEntryDetail(20, "123456789", "1313131313", 22.505M, "ID Number", "ID Name", "Desc Data"))
			{

			}
		}
		using (var bw2 = nachaWriter.CreateBatch(200))
		{
		}
	}
}
```

**Comment by RoushIT** [comment]
Write like this 


ChoNACHAConfiguration config = new ChoNACHAConfiguration();
config.DestinationBankRoutingNumber = "123456789";
config.OriginatingCompanyId = "123456789";
config.DestinationBankName = "PNC Bank";
config.OriginatingCompanyName = "Microsoft Inc.";
config.ReferenceCode = "Internal Use Only.";
config.BlockCount = 10;

// Start your stream and writer
MemoryStream ms= new MemoryStream();
 StreamWriter writer= new StreamWriter(ms);

 	using (var nachaWriter = new ChoNACHAWriter(writer, config))
 	{
 		using (var bw1 = nachaWriter.CreateBatch(200))
 		{
 			using (var entry1 = bw1.CreateDebitEntryDetail(20, "123456789", "1313131313", 22.505M, "ID Number", "ID Name", "Desc Data"))
 			{
 				entry1.CreateAddendaRecord("Monthly bill");
 			}
 			using (var entry2 = bw1.CreateCreditEntryDetail(20, "123456789", "1313131313", 22.505M, "ID Number", "ID Name", "Desc Data"))
 			{
 
 			}
 		}
 		using (var bw2 = nachaWriter.CreateBatch(200))
 		{
 		}
	}


//Flushes the write and returns the data to the original stream
 writer.Flush();

//Now your memorystream is populated;
var look = ms.ToArray();

**Comment by RoushIT** [comment]
Write like this

ChoNACHAConfiguration config = new ChoNACHAConfiguration();
config.DestinationBankRoutingNumber = "123456789";
config.OriginatingCompanyId = "123456789";
config.DestinationBankName = "PNC Bank";
config.OriginatingCompanyName = "Microsoft Inc.";
config.ReferenceCode = "Internal Use Only.";
config.BlockCount = 10;

// Start your stream and writer
MemoryStream ms= new MemoryStream();
StreamWriter writer= new StreamWriter(ms);

using (var nachaWriter = new ChoNACHAWriter(writer, config))
{
	using (var bw1 = nachaWriter.CreateBatch(200))
	{
		using (var entry1 = bw1.CreateDebitEntryDetail(20, "123456789", "1313131313", 22.505M, "ID Number", "ID Name", "Desc Data"))
		{
			entry1.CreateAddendaRecord("Monthly bill");
		}
		using (var entry2 = bw1.CreateCreditEntryDetail(20, "123456789", "1313131313", 22.505M, "ID Number", "ID Name", "Desc Data"))
		{

		}
	}
	using (var bw2 = nachaWriter.CreateBatch(200))
	{
	}
}

//Flushes the write and returns the data to the original stream
writer.Flush();

//Now your memorystream is populated;
var look = ms.ToArray();

**Comment by tkennedy13** [comment]
> RoushIT

Thanks! This solution worked great!
