### ISSUE TITLE
Missing Space in Header

### ISSUE THREAD

**Issue by tkennedy13** [Cinchoo/ChoETL.NACHA#28]
I'm trying to write an ACH file but for some reason I am not getting a space on the file header line  between the Priority Code and the Immediate Destination. I've tried different configuration options but I haven't been able to find the right one.

This is what I'm expecting:
101 888888888 777777777 1912061623A094101FIRST BANK             SOME COMPANY NAME              

but this is what I'm getting:
101888888888 777777777 1912061623A094101FIRST BANK             SOME COMPANY NAME              

Here is the code I'm using to generate the file:
```c#
ChoNACHAConfiguration config = new ChoNACHAConfiguration
{
	DestinationBankRoutingNumber = "88888888",
	OriginatingCompanyId = "777777777",
	DestinationBankName = "FIRST BANK",
	OriginatingCompanyName = "SOME COMPANY NAME",
	BlockingFactor = 10,
	ErrorMode = ChoErrorMode.ThrowAndStop,
};

using ( var nachaWriter = new ChoNACHAWriter( FileName, config ) )
{
	using ( var bw1 = nachaWriter.CreateBatch( 200 ) )
	{
		int idnum = 1;

		// Add info for each application
		foreach ( var app in applications )
		{
			// Transaction Code, Routing Number, Account Number, Amount, ID Number, Name, [Descritionary Info]
			using ( var entry = bw1.CreateDebitEntryDetail( transactionCode, app.DepositForm.RoutingNumber,
															app.DepositForm.AccountNumber,
															22.505M, idnum.ToString(), app.FirstName.ToUpper() + " " + app.LastName.ToUpper() ) )
			{
			}

			// Increment the ID number
			idnum++;
		}
	}
}
```

Am I doing something wrong? The test file I have from the bank has the space as does the example in the https://github.com/Cinchoo/ChoETL.NACHA/blob/master/ChoETL.NACHATest/20151027B0000327P018CHK.ACH.

**Comment by Cinchoo** [comment]
Here is the fix. Add space at the beginning of routing number.

```
ChoNACHAConfiguration config = new ChoNACHAConfiguration
{
	DestinationBankRoutingNumber = " 88888888",
	OriginatingCompanyId = "777777777",
	DestinationBankName = "FIRST BANK",
	OriginatingCompanyName = "SOME COMPANY NAME",
	BlockingFactor = 10,
	ErrorMode = ChoErrorMode.ThrowAndStop,
};
```

**Comment by kmehmoodkhan** [comment]
Yes - it's helpful. I was able to fix this.
