### ISSUE TITLE
company names are different

### ISSUE THREAD

**Issue by kmehmoodkhan** [Cinchoo/ChoETL.NACHA#29]
![image](https://user-images.githubusercontent.com/27416360/73386483-ba18e780-42f0-11ea-8afe-848f2583ce96.png)

in the above screenshot, there are two company names underlined. I don't know how to set two company names in the config while "ChoNACHAConfiguration" class is allowing us to set "OriginatingCompanyName" only. Kindly guide how to achieve this

**Comment by Cinchoo** [comment]
When you create the batch using `CreateBatch` method, you can pass the company name. 

`nachaWriter.CreateBatch(200, companyName: "JR PROCUREMENT")
`

**Comment by kmehmoodkhan** [comment]
There is one more issue, the Total Credit amount is placed on Total Debit amount position
![image](https://user-images.githubusercontent.com/27416360/75180781-b7c67380-575e-11ea-8cfa-2076f597d0eb.png)

As per specification Position 33-44, Total Credit Entry Dollar Amount in Batch
As per specification Field 7, Position 44-55, Total Credit Entry Dollar Amount in File
[ACH_AB_20201902_090227.txt](https://github.com/Cinchoo/ChoETL.NACHA/files/4246203/ACH_AB_20201902_090227.txt)

For reference, I have attached the file

**Comment by kmehmoodkhan** [comment]
Thank you very much for your help. Your support is absolutely outstanding.
