### ISSUE TITLE
Using DestinationBankName for "ImmediateDestinationName" and "ImmediateOriginName" in Header

### ISSUE THREAD

**Issue by etwina** [Cinchoo/ChoETL.NACHA#3]
Now:
![image](https://cloud.githubusercontent.com/assets/3801343/24481739/1c6d810c-14f5-11e7-81c4-d8edbc88bc4d.png)

Should Be:
![image](https://cloud.githubusercontent.com/assets/3801343/24481761/541bbcb8-14f5-11e7-8576-ee14f6a097b9.png)

**Comment by Cinchoo** [comment]
Possible mistake. Will correct and update the source. Thanks for reporting it. Appreciate your help.

**Comment by Cinchoo** [comment]
Corrected. Updated the fix to repository.
