### ISSUE TITLE
EntryDetail TraceNumber Source Configuration

### ISSUE THREAD

**Issue by scss-jbillig** [Cinchoo/ChoETL.NACHA#39]
Thank you for your NACHA plug-in. It has saved us time implementing our own version.

In most cases `_configuration.DestinationBankRoutingNumber` for the beginning of the  *Entry Detail* `TraceNumber` works out fine, but we have come across some clients wanting to use the `OriginatingDFIID` instead. This Chase spec for example https://www.chase.com/content/dam/chaseonline/en/demos/cbo/pdfs/cbo_nacha_filespecs.pdf seems to utilize it (pages 8 and 9).

Would it make sense to maybe add a configuration enum for `EntryDetailTraceSource` with options of `DestinationBankRoutingNumber` or `OriginatingDFI`? I would be happy to make the code changes and pull request it.

If there is a way to handle this currently, please let me know.

Regards,

Jim

**Comment by Cinchoo** [comment]
Pls go ahead and make the change. Thanks for your help.
