### ISSUE TITLE
BlockCount calculation is invalid

### ISSUE THREAD

**Issue by etwina** [Cinchoo/ChoETL.NACHA#4]
test:
![image](https://cloud.githubusercontent.com/assets/3801343/25696153/c464c5de-30be-11e7-9dea-3a9300c2088d.png)
Result 
FileControl: BlockCount value is 1

FileControl: BlockCount value should be 2

Suggested solution:
![image](https://cloud.githubusercontent.com/assets/3801343/25696219/01a8fc12-30bf-11e7-87e5-6324b051cec1.png)

if you have better solution please advise

**Comment by Cinchoo** [comment]
Thanks for report it. Fixed the issue as below and applied to the Git

  if (Configuration.BlockingFactor > 0)
                _fileControlRecord.BlockCount = (ulong)(Math.Ceiling(_runningStatObject.TotalNoOfRecord / (Configuration.BlockingFactor * 1.0)));
