### ISSUE TITLE
ChoETL.NACHA.NETStandard Nuget package

### ISSUE THREAD

**Issue by ok1-ok1** [Cinchoo/ChoETL.NACHA#41]
Isn't this package in nuget uptodate?
For example, I cannot see below property in ChoNACHAConfiguration which was added in #39 
```
public ChoEntryDetailTraceSource EntryDetailTraceSource { get; set; }
```

**Comment by Cinchoo** [comment]
Pushed new package v1.0.2.1. 

Thanks for reporting.
