### ISSUE TITLE
Broken README Example

### ISSUE THREAD

**Issue by brian-pickens-web** [Cinchoo/ChoETL.NACHA#44]
Hello,

I'm simply trying to recreate the example in the README, however the ChoNACHAReader Enumerator appears to be of type `Object`, which means there is no `ToStringEx()` method actually. What am I missing?

![image](https://user-images.githubusercontent.com/3659859/121363453-9611e100-c8fc-11eb-8d69-e2710b62f894.png)

**Comment by brian-pickens-web** [comment]
Okay, I figured it out. `ToStringEx()` is an extension method in the ChoETL library. I simply needed to add the using statement.
`using ChoETL;`. I recommend updating README to include this to reduce confusion.

**Comment by brian-pickens-web** [comment]
Actually, my next logical question is, how do I use the reader to gain access to the records themselves without using reflection? I suspect the answer is also somewhere in the ChoETL library. But it would be nice to have an example in the README for how to access the records and their property values properly.

**Comment by Cinchoo** [comment]
Thanks for your feedback. Updated the readme. Review and let me know.

**Comment by brian-pickens-web** [comment]
That’s perfect.
